<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ynohW8-64b-one" name="HBTestesNG.TestCases.Test_VoiceAQ_Conference" tests="5" failures="4" timestamp="25 Aug 2017 12:06:21 GMT" time="443.137" errors="0">
  <testcase name="VoiceAQ_CConference_ToIRN_DifferentGroup" time="110.761" classname="HBTestesNG.TestCases.Test_VoiceAQ_Conference">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Conference to IRN on Different Group  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Conference to IRN on Different Group  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Conference.VoiceAQ_CConference_ToIRN_DifferentGroup(Test_VoiceAQ_Conference.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CConference_ToIRN_DifferentGroup -->
  <testcase name="VoiceAQ_CConference_ToExternal" time="110.749" classname="HBTestesNG.TestCases.Test_VoiceAQ_Conference">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Conference to External number has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Conference to External number has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Conference.VoiceAQ_CConference_ToExternal(Test_VoiceAQ_Conference.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CConference_ToExternal -->
  <testcase name="VoiceAQ_CConference_ToIRN_SameGroup" time="0.001" classname="HBTestesNG.TestCases.Test_VoiceAQ_Conference"/>
  <testcase name="VoiceAQ_CConference_ToExt_SameGroup" time="110.844" classname="HBTestesNG.TestCases.Test_VoiceAQ_Conference">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Conference to Ext on Same Group has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Conference to Ext on Same Group has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Conference.VoiceAQ_CConference_ToExt_SameGroup(Test_VoiceAQ_Conference.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CConference_ToExt_SameGroup -->
  <testcase name="VoiceAQ_CConference_ToExt_DifferentGroup" time="110.782" classname="HBTestesNG.TestCases.Test_VoiceAQ_Conference">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Conference to Ext on Different Group has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Conference to Ext on Different Group has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Conference.VoiceAQ_CConference_ToExt_DifferentGroup(Test_VoiceAQ_Conference.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CConference_ToExt_DifferentGroup -->
</testsuite> <!-- HBTestesNG.TestCases.Test_VoiceAQ_Conference -->
