<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ynohW8-64b-one" name="HBTestesNG.TestCases.Test_Chat_All" tests="12" failures="9" timestamp="26 Oct 2017 23:55:24 GMT" time="1544.420" errors="1">
  <testcase name="Chat_NoQ_Answer" time="100.256" classname="HBTestesNG.TestCases.Test_Chat_All"/>
  <testcase name="Chat_BTransfer_ByExt_SameGroup" time="137.187" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Ans-&gt;Blind Transfer to Ext on Same Group  has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Ans->Blind Transfer to Ext on Same Group  has failed because => [agent1yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_BTransfer_ByExt_SameGroup(Test_Chat_All.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_BTransfer_ByExt_SameGroup -->
  <testcase name="Chat_Q_Overflow_R_Ans_1stGroup" time="166.451" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Q-&gt;Overflow-&gt;Ring-&gt;Answer on the 2nd group has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent2yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent4yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent1yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Q->Overflow->Ring->Answer on the 2nd group has failed because => [agent1yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent2yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent4yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent1yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_Q_Overflow_R_Ans_1stGroup(Test_Chat_All.java:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_Q_Overflow_R_Ans_1stGroup -->
  <testcase name="Chat_R_Q_Overflow_R_Ans_2ndGroup" time="155.839" classname="HBTestesNG.TestCases.Test_Chat_All"/>
  <testcase name="Chat_NoQ_Answer_NoWrapTime" time="22.631" classname="HBTestesNG.TestCases.Test_Chat_All">
    <error type="org.openqa.selenium.WebDriverException" message="unknown error: Element &lt;input id=&quot;wrap_up_time&quot; name=&quot;__db_wrap_up_time&quot; type=&quot;text&quot; class=&quot;yui3-spinner-value hint&quot; value=&quot;20&quot; onkeypress=&quot;updateChangeFlag(true);&quot; onchange=&quot;updateChangeFlag(true);&quot; onkeyup=&quot;updateChangeFlag(true);&quot; title=&quot;&quot;&gt; is not clickable at point (514, 659). Other element would receive the click: &lt;div id=&quot;rightWrapper&quot; style=&quot;top: 46px;&quot;&gt;...&lt;/div&gt;
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 243 milliseconds
Build info: version: &#039;2.53.0&#039;, revision: &#039;35ae25b&#039;, time: &#039;2016-03-15 16:57:40&#039;
System info: host: &#039;ynohW8-64b-one&#039;, ip: &#039;10.23.176.230&#039;, os.name: &#039;Windows 8&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.2&#039;, java.version: &#039;1.8.0_65&#039;
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a), userDataDir=C:\Users\shoretel\AppData\Local\Temp\scoped_dir4188_20447}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=61.0.3163.100, platform=WIN8, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 8e2ab06158121d3a0ff89a5181fad9d7">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <input id="wrap_up_time" name="__db_wrap_up_time" type="text" class="yui3-spinner-value hint" value="20" onkeypress="updateChangeFlag(true);" onchange="updateChangeFlag(true);" onkeyup="updateChangeFlag(true);" title=""> is not clickable at point (514, 659). Other element would receive the click: <div id="rightWrapper" style="top: 46px;">...</div>
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 243 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'ynohW8-64b-one', ip: '10.23.176.230', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a), userDataDir=C:\Users\shoretel\AppData\Local\Temp\scoped_dir4188_20447}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=61.0.3163.100, platform=WIN8, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 8e2ab06158121d3a0ff89a5181fad9d7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
	at HBTestesNG.BaseObjects.Agent.retryClickXPath(Agent.java:416)
	at HBTestesNG.BaseObjects.Agent.clickAndSelectAllByXPath(Agent.java:630)
	at HBTestesNG.BaseObjects.Agent.typeElementXPath(Agent.java:564)
	at HBTestesNG.BaseObjects.AgentHBDirector.Max_LogIn_changeWrapAndFRTime_Min(AgentHBDirector.java:335)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_NoQ_Answer_NoWrapTime(Test_Chat_All.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- Chat_NoQ_Answer_NoWrapTime -->
  <testcase name="Chat_BTransfer_ByAgentName_SameGroup" time="136.546" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Ans-&gt;Blind Transfer by agent name on Same Group  has failed because =&gt; [agent2yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent2yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Ans->Blind Transfer by agent name on Same Group  has failed because => [agent2yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent2yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_BTransfer_ByAgentName_SameGroup(Test_Chat_All.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_BTransfer_ByAgentName_SameGroup -->
  <testcase name="Chat_Q_Overflow_R_Ans_2ndGroup" time="160.114" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Q-&gt;Overflow-&gt;Ring-&gt;Answer on the 2nd group has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent4yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Q->Overflow->Ring->Answer on the 2nd group has failed because => [agent1yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent4yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_Q_Overflow_R_Ans_2ndGroup(Test_Chat_All.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_Q_Overflow_R_Ans_2ndGroup -->
  <testcase name="Chat_Q_OverInterflow_Q_R_Ans_3rdGroup" time="227.128" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Q-&gt;OverInterflow-&gt;Q-&gt;Ring-&gt;Answer on the 3rd group has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent2yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent4yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent4yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Q->OverInterflow->Q->Ring->Answer on the 3rd group has failed because => [agent1yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent2yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent4yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent4yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_Q_OverInterflow_Q_R_Ans_3rdGroup(Test_Chat_All.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_Q_OverInterflow_Q_R_Ans_3rdGroup -->
  <testcase name="Chat_Q_Answer" time="117.404" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Q-&gt;Answered has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Q->Answered has failed because => [agent1yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_Q_Answer(Test_Chat_All.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_Q_Answer -->
  <testcase name="Chat_Queue_Abandon" time="66.879" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Queue-&gt;Disconnect has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent2yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Queue->Disconnect has failed because => [agent1yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent2yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_Queue_Abandon(Test_Chat_All.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_Queue_Abandon -->
  <testcase name="Chat_R_Q_Overflow_Q_R_Ans_2ndGroup" time="186.639" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Ring-&gt;Q-&gt;Overflow-&gt;Q-&gt;Ring-&gt;Answer on the 2nd group has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;, agent2yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent4yc1@c1yc1.com: AIC shows idle but still reads &quot; Stop taking requests &quot;, agent4yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Ring->Q->Overflow->Q->Ring->Answer on the 2nd group has failed because => [agent1yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests ", agent2yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent4yc1@c1yc1.com: AIC shows idle but still reads " Stop taking requests ", agent4yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_R_Q_Overflow_Q_R_Ans_2ndGroup(Test_Chat_All.java:308)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_R_Q_Overflow_Q_R_Ans_2ndGroup -->
  <testcase name="Chat_Ring_Abandon" time="67.346" classname="HBTestesNG.TestCases.Test_Chat_All">
    <failure type="java.lang.AssertionError" message="Chat-&gt;Ring-&gt;Disconnect has failed because =&gt; [agent1yc1@c1yc1.com: AIC shows Released but still reads &quot; Start taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Chat->Ring->Disconnect has failed because => [agent1yc1@c1yc1.com: AIC shows Released but still reads " Start taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:440)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:218)
	at HBTestesNG.TestCases.Test_Chat_All.Chat_Ring_Abandon(Test_Chat_All.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Chat_Ring_Abandon -->
</testsuite> <!-- HBTestesNG.TestCases.Test_Chat_All -->
