<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ynohW8-64b-one" name="HBTestesNG.TestCases.Test_VoiceAQ_Transfer" tests="11" failures="11" timestamp="25 Aug 2017 12:06:21 GMT" time="1222.613" errors="0">
  <testcase name="VoiceAQ_BTransfer_ToIRN_SameGroup" time="110.669" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Blind Transfer to Ext on Same Group  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Blind Transfer to Ext on Same Group  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_BTransfer_ToIRN_SameGroup(Test_VoiceAQ_Transfer.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_BTransfer_ToIRN_SameGroup -->
  <testcase name="VoiceAQ_CTransfer_ToIRN_DifferentGroup" time="110.681" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Transfer to IRN on Different Group  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Transfer to IRN on Different Group  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_CTransfer_ToIRN_DifferentGroup(Test_VoiceAQ_Transfer.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CTransfer_ToIRN_DifferentGroup -->
  <testcase name="VoiceAQ_BTransfer_ToExternal" time="110.729" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Blind Transfer to External number  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Blind Transfer to External number  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_BTransfer_ToExternal(Test_VoiceAQ_Transfer.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_BTransfer_ToExternal -->
  <testcase name="VoiceAQ_BTransfer_ToExt_SameGroup" time="110.719" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Blind Transfer to Ext on Same Group  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Blind Transfer to Ext on Same Group  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_BTransfer_ToExt_SameGroup(Test_VoiceAQ_Transfer.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_BTransfer_ToExt_SameGroup -->
  <testcase name="VoiceAQ_CTransfer_ToExt_SameGroup" time="110.790" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Transfer to Ext on Same Group has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Transfer to Ext on Same Group has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_CTransfer_ToExt_SameGroup(Test_VoiceAQ_Transfer.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CTransfer_ToExt_SameGroup -->
  <testcase name="VoiceAQ_CTransfer_ToIRN_SameGroup" time="110.781" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Transfer to IRN on Same Group  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Transfer to IRN on Same Group  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_CTransfer_ToIRN_SameGroup(Test_VoiceAQ_Transfer.java:372)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CTransfer_ToIRN_SameGroup -->
  <testcase name="VoiceAQ_CTransfer_ToExt_DifferentGroup" time="110.800" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Transfer to Ext on Different Group has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Transfer to Ext on Different Group has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_CTransfer_ToExt_DifferentGroup(Test_VoiceAQ_Transfer.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CTransfer_ToExt_DifferentGroup -->
  <testcase name="VoiceAQ_BTransfer_ToIRN_AQ" time="110.779" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Blind Transfer to IRN to AQ  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Blind Transfer to IRN to AQ  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_BTransfer_ToIRN_AQ(Test_VoiceAQ_Transfer.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_BTransfer_ToIRN_AQ -->
  <testcase name="VoiceAQ_BTransfer_ToExt_DifferentGroup" time="110.791" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Blind Transfer to Ext on Different Group  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Blind Transfer to Ext on Different Group  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_BTransfer_ToExt_DifferentGroup(Test_VoiceAQ_Transfer.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_BTransfer_ToExt_DifferentGroup -->
  <testcase name="VoiceAQ_CTransfer_ToExternal" time="115.205" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Consult Transfer to External number has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Consult Transfer to External number has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_CTransfer_ToExternal(Test_VoiceAQ_Transfer.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_CTransfer_ToExternal -->
  <testcase name="VoiceAQ_BTransfer_ToIRN_DifferentGroup" time="110.669" classname="HBTestesNG.TestCases.Test_VoiceAQ_Transfer">
    <failure type="java.lang.AssertionError" message="VoiceAQ-&gt;Ans-&gt;Blind Transfer to Ext on Different Group  has failed because =&gt; start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceAQ->Ans->Blind Transfer to Ext on Different Group  has failed because => start_good;# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes# agent2yc1@c1yc1.comfail on wrapupEndWith2WrapupCodes expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceAQ_Transfer.VoiceAQ_BTransfer_ToIRN_DifferentGroup(Test_VoiceAQ_Transfer.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceAQ_BTransfer_ToIRN_DifferentGroup -->
</testsuite> <!-- HBTestesNG.TestCases.Test_VoiceAQ_Transfer -->
