<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ynohW8-64b-one" name="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero" tests="7" failures="2" timestamp="17 Oct 2017 19:52:46 GMT" time="1066.120" errors="0">
  <testcase name="VoiceOACD_ByAbandon_CConference_ToIRN_SameGroup" time="0.001" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero"/>
  <testcase name="VoiceOACD_ByAbandon_CConference_ToExternal" time="176.779" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero"/>
  <testcase name="VoiceOACD_ByAbandon_CConference_ToIRN_DifferentGroup" time="181.859" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero">
    <failure type="java.lang.AssertionError" message="VoiceOACD_ByAbandon-&gt;Ans-&gt;Consult Conference to IRN on Different Group_WrapTimeZero has failed because =&gt; [agent2yc1@c1yc1.com: AIC shows idle, but it still says &quot; Stop taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceOACD_ByAbandon->Ans->Consult Conference to IRN on Different Group_WrapTimeZero has failed because => [agent2yc1@c1yc1.com: AIC shows idle, but it still says " Stop taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:464)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:243)
	at HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero.VoiceOACD_ByAbandon_CConference_ToIRN_DifferentGroup(Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceOACD_ByAbandon_CConference_ToIRN_DifferentGroup -->
  <testcase name="VoiceOACD_ByAbandon_CConference_ToExt_DifferentGroup_byName" time="174.227" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero">
    <failure type="java.lang.AssertionError" message="VoiceOACD_ByAbandon-&gt;Ans-&gt;Consult Conference to Ext on Different Group_byName has failed because =&gt; [agent2yc1@c1yc1.com: AIC shows idle, but it still says &quot; Stop taking reauests &quot;] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceOACD_ByAbandon->Ans->Consult Conference to Ext on Different Group_byName has failed because => [agent2yc1@c1yc1.com: AIC shows idle, but it still says " Stop taking reauests "] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:464)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:243)
	at HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero.VoiceOACD_ByAbandon_CConference_ToExt_DifferentGroup_byName(Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero.java:319)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceOACD_ByAbandon_CConference_ToExt_DifferentGroup_byName -->
  <testcase name="VoiceOACD_ByAbandon_CConference_ToExt_SameGroup" time="179.288" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero"/>
  <testcase name="VoiceOACD_ByAbandon_CConference_ToExt_SameGroup_byName" time="179.499" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero"/>
  <testcase name="VoiceOACD_ByAbandon_CConference_ToExt_DifferentGroup" time="174.467" classname="HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero"/>
</testsuite> <!-- HBTestesNG.TestCases.Test_VoiceOACD_ByAbandon_Conference_WrapTimeZero -->
